import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail, FileText, ListChecks, Search, MessagesSquare, Sparkles, ArrowRight } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — Workplace AI" },
      { name: "description", content: "Your AI workplace productivity dashboard." },
    ],
  }),
  component: Dashboard,
});

const features = [
  { to: "/email", title: "Smart Email Generator", desc: "Draft professional emails from a few key points.", icon: Mail },
  { to: "/meetings", title: "Meeting Notes Summarizer", desc: "Turn raw notes into clear summaries and action items.", icon: FileText },
  { to: "/tasks", title: "AI Task Planner", desc: "Break goals into prioritized, actionable plans.", icon: ListChecks },
  { to: "/research", title: "AI Research Assistant", desc: "Get structured briefings on any topic.", icon: Search },
  { to: "/chat", title: "AI Chatbot", desc: "Ask anything — brainstorm, plan, draft, decide.", icon: MessagesSquare },
] as const;

function Dashboard() {
  return (
    <div className="mx-auto max-w-6xl">
      <section className="relative overflow-hidden rounded-2xl border bg-card p-6 shadow-[var(--shadow-card)] md:p-10">
        <div className="absolute inset-0 -z-10 opacity-[0.07] bg-[image:var(--gradient-primary)]" />
        <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-primary">
          <Sparkles className="h-3.5 w-3.5" /> AI Productivity Suite
        </div>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">
          Get more done with your AI co-worker.
        </h1>
        <p className="mt-3 max-w-2xl text-muted-foreground">
          Generate emails, summarize meetings, plan tasks, run research, and chat — all in one
          clean workspace built for professionals.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <Link
            to="/chat"
            className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-[var(--shadow-elegant)] transition hover:opacity-90"
          >
            Start chatting <ArrowRight className="h-4 w-4" />
          </Link>
          <Link
            to="/email"
            className="inline-flex items-center gap-2 rounded-md border bg-background px-4 py-2 text-sm font-medium transition hover:bg-accent"
          >
            Draft an email
          </Link>
        </div>
      </section>

      <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {features.map((f) => (
          <Link
            key={f.to}
            to={f.to}
            className="group rounded-xl border bg-card p-5 shadow-[var(--shadow-card)] transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-[var(--shadow-elegant)]"
          >
            <div className="grid h-10 w-10 place-items-center rounded-lg bg-accent text-accent-foreground transition group-hover:bg-[image:var(--gradient-primary)] group-hover:text-primary-foreground">
              <f.icon className="h-5 w-5" />
            </div>
            <div className="mt-4 flex items-center justify-between">
              <h3 className="font-semibold">{f.title}</h3>
              <ArrowRight className="h-4 w-4 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" />
            </div>
            <p className="mt-1.5 text-sm text-muted-foreground">{f.desc}</p>
          </Link>
        ))}
      </section>

      <section className="mt-8 rounded-xl border bg-muted/40 p-5 text-sm text-muted-foreground">
        <strong className="font-medium text-foreground">Responsible AI:</strong>{" "}
        Outputs are generated by AI and may be inaccurate, incomplete, or biased. Always review
        and edit before sending, sharing, or acting on them. Avoid entering confidential or
        regulated information unless your organization permits it.
      </section>
    </div>
  );
}
